CREATE OR REPLACE VIEW `production-dashboard-482014.dashboard_data.rejection_analysis`
AS
SELECT
  COALESCE(
    SAFE.PARSE_DATE('%Y-%m-%d', CAST(vqc_inward_date AS STRING)),
    SAFE.PARSE_DATE('%d-%m-%Y', CAST(vqc_inward_date AS STRING)),
    SAFE.PARSE_DATE('%d-%m-%y', CAST(vqc_inward_date AS STRING)),
    SAFE_CAST(vqc_inward_date AS DATE)
  ) AS date,
  vendor,
  vqc_reason,
  CASE
    WHEN vqc_reason IN ('BLACK GLUE', 'ULTRAHUMAN TEXT SMUDGED', 'WHITE PATCH ON BATTERY', 'WHITE PATCH ON PCB', 'WHITE PATCH ON BLACK TAPE', 'WRONG RX COIL') THEN 'ASSEMBLY'
    WHEN vqc_reason IN ('MICRO BUBBLES', 'ALIGNMENT ISSUE', 'DENT ON RESIN', 'DUST INSIDE RESIN', 'RESIN CURING ISSUE', 'SHORT FILL OF RESIN', 'SPM REJECTION', 'TIGHT FIT FOR CHARGE', 'LOOSE FITTING ON CHARGER', 'RESIN SHRINKAGE', 'WRONG MOULD', 'GLOP TOP ISSUE') THEN 'CASTING'
    WHEN vqc_reason IN ('100% ISSUE', '3 SENSOR ISSUE', 'BATTERY ISSUE', 'BLUETOOTH HEIGHT ISSUE', 'CE TAPE ISSUE', 'CHARGING CODE ISSUE', 'COIL THICKNESS ISSUE/BATTERY THICKNESS', 'COMPONENT HEIGHT ISSUE', 'CURRENT ISSUE', 'DISCONNECTING ISSUE', 'HRS BUBBLE', 'HRS COATING HEIGHT ISSUE', 'HRS DOUBLE LIGHT ISSUE', 'HRS HEIGHT ISSUE', 'NO NOTIFICATION IN CDT', 'NOT ADVERTISING (WINGLESS PCB)', 'PRE NA', 'POST NA', 'NOT CHARGING', 'SENSOR ISSUE', 'STC ISSUE', 'R&D REJECTION') THEN 'FUNCTIONAL'
    WHEN vqc_reason IN ('IMPROPER RESIN FINISH', 'RESIN DAMAGE', 'RX COIL SCRATCH', 'SCRATCHES ON RESIN', 'SIDE SCRATCH', 'SIDE SCRATCH (EMERY)', 'SHELL COATING REMOVED', 'UNEVEN POLISHING', 'WHITE PATCH ON SHELL AFTER POLISHING', 'SCRATCHES ON SHELL') THEN 'POLISHING'
    WHEN vqc_reason IN ('BLACK MARKS ON SHELL', 'DENT ON SHELL', 'DISCOLORATION', 'IRREGULAR SHELL SHAPE', 'SHELL COATING ISSUE', 'WHITE MARKS ON SHELL') THEN 'SHELL'
    ELSE 'OTHER'
  END AS rejection_category,
  COUNT(*) AS count
FROM
  `production-dashboard-482014.dashboard_data.master_station_data`
WHERE
  vqc_inward_date IS NOT NULL
  AND vqc_reason IS NOT NULL
GROUP BY
  1, 2, 3, 4